### ISSUE TITLE
Make the InjectionService functions asynchronous

### ISSUE THREAD

**Issue by ABridoux** [ABridoux/lux#24]
It might be better to execute the parsing in the background for long files or strings. Then the output will be send in a completion handler.

**Comment by Ethenyl** [comment]
This can be done in multiple way, we could use `NSOperationQueue` for that, it's perfectly suited for concurrent work.

I try to avoid adding external framework as much as possible but we could also improve this by using `ProcedureKit` which is superseding `NSOperationQueue` by improving operations with observers, input/output capabilities, grouping, etc.

It's up to you ;-)

**Comment by ABridoux** [comment]
Right. As it is only one callback, I was thinking about the `NSOperationQueue`. But if it starts to be more complex, we should definitely use something like `PocedureKit`  as you offered.

**Comment by ABridoux** [comment]
After having tested it, I ended up thinking that it is not relevant to add the complexity of asynchronous. The program is really fast and the fact that `NSRegularExpression` does not need asynchronous processes also indicates that it's not needed I think. I may be wrong though. But for now, the functions will remain synchronous.
